# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publishing_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 10, 14, 9, 22, 51, 842592)),
        ),
    ]
